### ISSUE TITLE
b ug

### ISSUE THREAD

**Issue by Muscliy** [DLopezOpentix/example-cordova-code-push-plugin#1]
the release commands are incorrect
`code-push release-cordova <appname> <platform> -t 1.0.8 -d Staging` 
code-push has three diff deployment command
release          Release an update to an app deployment
  release-cordova  Release a Cordova update to an app deployment
  release-react    Release a React Native update to an app deployment
 if cordova project use release , u cannot get correct update info  from its server in device

**Comment by Dellos7** [comment]
Hello,

The CLI command `code-push release-cordova...` works, but it also works the `code-push release ...` that it's in the example. You can try it yourself if you want.

I faced some issues using the `code-push release-cordova ...` command and I prefer doing it this way. The ones that are in the README are the commands that I use each week in order to release the updates of my Ionic apps.

Thank you.
